DROP TABLE IF EXISTS CONTA;
CREATE TABLE CONTA(
  ID INT PRIMARY KEY,
  NOME VARCHAR2(50) NOT NULL,
  PESSOA_TIPO VARCHAR2(14) NOT NULL,
  TIPO_CONTA CHAR NOT NULL,
  STATUS CHAR NOT NULL
);

DROP TABLE IF EXISTS PESSOA;
CREATE TABLE PESSOA(
  ID INT PRIMARY KEY,
  TIPO_PESSOA VARCHAR2(14) NOT NULL
);

DROP TABLE IF EXISTS PJ;
CREATE TABLE PJ(
  ID INT PRIMARY KEY,
  RAZAO_SOCIAL VARCHAR2(50) NOT NULL,
  NOME_FANTASIA VARCHAR2(50) NOT NULL,
  CNPJ VARCHAR2(14) NOT NULL,
);

DROP TABLE IF EXISTS PF;
CREATE TABLE PF(
  ID INT PRIMARY KEY,
  NOME VARCHAR2(50) NOT NULL,
  CPF VARCHAR2(11) NOT NULL,
  DATA_NASCIMENTO TIMESTAMP,
);

DROP TABLE IF EXISTS AUDIT;
CREATE TABLE AUDIT(
  ID INT PRIMARY KEY,
  DATA_CRIACAO TIMESTAMP NOT NULL,
  DATA_ATUALIZACAO TIMESTAMP NOT NULL,
  PESSOA VARCHAR2(14) NOT NULL
);

DROP TABLE IF EXISTS MOVIMENTACAO;
CREATE TABLE MOVIMENTACAO(
  ID INT PRIMARY KEY,
  DEPOSITO BIGINT,
  SAQUE BIGINT,
  PESSOA VARCHAR2(14)
);

ALTER TABLE CONTA
  ADD FOREIGN KEY (PESSOA_TIPO) REFERENCES PESSOA(TIPO_PESSOA);

ALTER TABLE PJ
  ADD FOREIGN KEY (CNPJ) REFERENCES PESSOA(TIPO_PESSOA);

ALTER TABLE PF
  ADD FOREIGN KEY (CPF) REFERENCES PESSOA(TIPO_PESSOA);

ALTER TABLE AUDIT
  ADD FOREIGN KEY (PESSOA) REFERENCES PESSOA(TIPO_PESSOA);

ALTER TABLE MOVIMENTACAO
  ADD FOREIGN KEY (PESSOA) REFERENCES PESSOA(TIPO_PESSOA);

INSERT INTO PESSOA VALUES (1,'CPF');
UPDATE PESSOA set TIPO_PESSOA = 'PF' where ID = 1;
INSERT INTO PESSOA VALUES (2,'CNPJ');
UPDATE PESSOA set TIPO_PESSOA = 'PJ' where ID = 2;

select * from PESSOA;

INSERT INTO CONTA VALUES (1, 'CONTA 1', 'PF', 'M', 'A');
INSERT INTO CONTA VALUES (2, 'CONTA 2', 'PJ', 'M', 'A');
select * from CONTA;